spring.application.name=backend
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PrepAce;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=123456

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=cuuthangnguyen1210@gmail.com
spring.mail.password=yasbyteijcelngxo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
google.client.id=257199987910-2tfe97p674iljqh5uqbgpvqe5b3a55dl.apps.googleusercontent.com
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
server.port=8080
sepay.api-key=${5Q5XJOSGR4HQW9ZPMIJYZSABBT4UYLXEJ03RIFA8RXPC3FUN2THCMCDSPOLKO71Z}
# Ép Hibernate giữ nguyên chính xác tên bảng viết hoa/viết thường như cấu hình ở @Table
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl

# File Upload Limit Configuration
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Cloudinary Configuration
cloudinary.cloud-name=desnyjgxp
cloudinary.api-key=458683156277599
cloudinary.api-secret=PQW71bOcw8f70YZVb-Q1c8oOzIk

# ── Gemini AI ──────────────────────────────────────────────────────────────────
# Lấy API key tại: https://aistudio.google.com/app/apikey
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/
gemini.api.key=AQ.Ab8RN6JOJOZ2ZdZC4YYNfHDa78L1NGpGbpwoNne-UESkvZcuWg

spring.task.scheduling.pool.size=5
}'
